polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path(r'<int:question_id>/', views.detail, name='detail'),
    path(r'more/detail/<int:question_id>/<str:extra_word>/', views.more_detail, name='more_detail'),
    path(r'<int:question_id>/results/', views.results, name='results'),
    path(r'<int:question_id>/vote/', views.vote, name='vote'),
    path(r'question/list/', views.question_list, name='question_list'),
    path(r'shortcut/question/list/', views.question_list_shortcut, name='question_list_shortcut'),
    path(r'deliberate/404/', views.deliberate_404, name='deliberate_404'),
    path(r'raise/404/if/<int:question_id>/does/not/exist/', views.raise_404_if_question_does_not_exist, name='raise_404_if_question_DNE'),
    path(r'link/library/', views.link_library, name='link_library'),
    path(r'minimal/form/<int:question_id>/', views.minimal_form, name='minimal_form'),
    path(r'v2/<int:question_id>/', views.v2, name='v2'),
    
    path(r'show/all/choices', views.show_all_choices, name='show_all_choices'),
    
    path(r'', views.index, name='index'),
]

polls/models.py
"""
Django uses the model code to:
    (1) Create a DB schema
    (2) Create a Python DB-access API for accessing objects
"""
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(r'date published')
    
    def __str__(self):
        """This method is used throughout Django's auto-generated admin."""
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        """This method is used throughout Django's auto-generated admin."""
        return self.choice_text

polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.http.request import HttpRequest
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse

from .models import Question, Choice


def index(request):
    return HttpResponse(r"Hello World! Python and AWS are awesome!")


def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)


def more_detail(request, question_id, extra_word):
    return HttpResponse(str("question_id = " + str(question_id) + "<br/>extra_word = " + str(extra_word)))


def question_list(request):
    question_list = Question.objects.all()
    template = loader.get_template('polls/question_list.html')
    context = {
        'question_list': question_list
    }
    return HttpResponse(template.render(context, request))


def question_list_shortcut(request):
    question_list = Question.objects.all()
    return render(request, 'polls/question_list.html', {
        'question_list': question_list
    })
    

def deliberate_404(request):
    raise Http404("Deliberate 404")
    return

    
def raise_404_if_question_does_not_exist(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return HttpResponse('Question exists --> ' + question.question_text)


def link_library(request):
    return render(request, 'polls/link_library.html')


def minimal_form(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/minimal_form.html', {
        'question': question
    })
    
    
def v2(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/minimal_form.html', {
            'question': question,
            'error_message': 'Select a valid choice'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:show_all_choices'))
    

def show_all_choices(request):
    choices = Choice.objects.all()
    return render(request, 'polls/show_all_choices.html', {
        'choices': choices
    })
    

polls/templates/polls/link_library.html
<h1>Polls App</h1>
<h2>Link Library Page</h2>

<ul>
	<li><a href="{% url 'polls:detail' 1 %}">Detail page with question_id equal to 1</li>
	<li><a href="{% url 'polls:more_detail' 1 'Hello' %}">More Detail page with question_id equal to 1 and extra word equal to Hello</li>
	<li><a href="{% url 'polls:deliberate_404' %}">Deliberate 404 page</li>
</ul>

polls/templates/polls/minimal_form.html
<h1>Polls App</h1>
<h2>Minimal Form Page</h2>

{% if error_message %}
	<p style="color:red">{{ error_message }}</p>
{% endif %}

<form action="{% url 'polls:v2' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type="radio" 
				name="choice" 
				id="choice{{ forloop.counter }}" 
				value="{{choice.id}}"
		<label for="choice{{ forloop.counter }}">
			{{ choice.choice_text }}
		</label>
		<br />
	{% endfor %}
	<input type="submit" value="vote" />
</form>

polls/templates/polls/question_list.html
<h1>Polls App</h1>
<h2>Question List Page</h2>

<p>The view model is a list of question_text</p>

{% if question_list %}
	<ul>
	{% for question in question_list %}
		<li>{{ question.question_text }}</li>
	{% endfor %}
	</ul>
{% else %}
	<p>There are no questions</p>
{% endif %}

polls/templates/polls/show_all_choices.html
<h1>Polls App</h1>
<h2>Show All Choices Page</h2>
<br />

<h4>Choices:</h4>

{% if choices %}
	{% for choice in choices %}
		<p>{{ choice.choice_text }}&nbsp;=&nbsp;{{ choice.votes }} votes</p>
	{% endfor %}
{% else %}
	<p>There are no choices</p>
{% endif %}
<br />

<h4><a href="{% url 'polls:minimal_form' 1 %}">Minimal Form Page</a></h4>